### PR TITLE
Update docs for excludeTopology config

### PR DESCRIPTION
**Pull request by rthakur-est**
Updated README to include documentation for "excludeTopology" config.
This config allows making advertising of device's NUMA toplogy optional.

#320 

Signed-off-by: Ravindra Thakur <ravindra.nath.thakur@est.tech>

### CODE REVIEW

**Review by adrianchiris — APPROVED** [review]
CI failure is un-related

LGTM

should be merged once #416 is merged
should be merged once #

**Review by Eoghan1232 — APPROVED** [review]
LGTM

**Comment by Eoghan1232** [comment]
@SchSeba are you happy to merge this too?

**Comment by zeeke** [comment]
LGTM

**Pull request merged**
