### PR TITLE
remove vendoring, use Go modules by default

### PR DESCRIPTION
**Pull request by jaypipes**
Removes the vendor/ directory and all vestiges of life before Go modules.

Also updates pkg/utils/testing.go to properly account for non-RHEL
systems, which typically store the pci.ids file at
/usr/share/misc/pci.ids instead of /usr/share/hwdata/pci.ids.

Addresses golint warnings around grpc.DialContext being deprecated by
replacing calls with grpc.NewClient.

Issue #544

### CODE REVIEW

**Comment by zeeke** [comment]
hi @jaypipes , can you please rebase and run 
```
go mod tidy
```

**Comment by jaypipes** [comment]
@zeeke np, all done.

**Comment by SchSeba** [comment]
The linters are not happy can you please take a look?

**Comment by jaypipes** [comment]
@SchSeba apologies for the long delay in getting back to this! Rebased from main which should fix any linter failures.

**Review by e0ne — APPROVED** [review]
LGTM

**Comment by jaypipes** [comment]
@zeeke @SchSeba Hi! :) Can we run the gate tests on this PR please? Thanks in advance!

**Review by adrianchiris — APPROVED** [review]

**Review by zeeke — APPROVED** [review]
LGTM

**Pull request merged**
