### PR TITLE
Run "go mod vendor" for disconnected builds

### PR DESCRIPTION
**Pull request by wizhaoredhat**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
/cc @SchSeba
/cc @zeeke 
/cc @adrianchiris 

PTAL. We need the vendor directory to be updated for our disconnected builds for openshift.

**Comment by adrianchiris** [comment]
@wizhaoredhat can you "go mod vendor" in openshift downstream fork ?

**Comment by SchSeba** [comment]
agree with @adrianchiris 
I think we can close this one

**Comment by wizhaoredhat** [comment]
> @wizhaoredhat can you "go mod vendor" in openshift downstream fork ?

Agreed we can close this. Thanks!

**Pull request closed without merging**
