### PR TITLE
remove dependency elazarl/goproxy

### PR DESCRIPTION
**Pull request by SalDaniele**
This commit updates a number of dependencies, namely k8s.io/apimachinery, in order to remove the dependency on the outdated package github.com/elazarl/goproxy

### CODE REVIEW

**Comment by SalDaniele** [comment]
@wizhao @bn222 PTAL

**Comment by bn222** [comment]
LGTM

**Review by zeeke — APPROVED** [review]
LGTM

**Comment by SalDaniele** [comment]
@zeeke Is it possible to merge this?

**Review by Eoghan1232 — APPROVED** [review]
lgtm

**Pull request merged**
