### PR TITLE
PCI address based filtering for accelerator device type is not supported

### PR DESCRIPTION
**Pull request by svallala**
Filtering based on PCI addresses is missing

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@svallala pciAddresses selector was added in favor of using sriov in VM environmnet, what is the use case for accelerator?

**Comment by svallala** [comment]
We would like to group the FPGA resources based on NUMA topology and since NUMA node is not part of the selectors the only way to achieve this via PCI Addresses. The documentation states that standard selectors are supported for accelerators and PCI Addresses is part of the standard selectors.

**Comment by zshi-redhat** [comment]
> We would like to group the FPGA resources based on NUMA topology and since NUMA node is not part of the selectors the only way to achieve this via PCI Addresses. The documentation states that standard selectors are supported for accelerators and PCI Addresses is part of the standard selectors.

Would k8s topology manager be helpful here if devices are not grouped based on NUMA?

**Comment by svallala** [comment]
We don't want to rely on Topology Manager, since we have advanced planning algorithm. This seems to be a genuine miss because the documentation explicitly mentions common selectors being supported for the accelerator device type.

**The "accelerator" device type currently supports only the common selectors.**

**Comment by svallala** [comment]
The use case could also be, to create resource grouping where a customer would like to have a few VFs reserved for a tenant. If for some reason this pull request is not approved, then at least the documentation should be fixed to indicate that PCI address based filtering is not supported for "accelerator" device types. I didn't suspect a plugin issue and had to spend a lot of time debugging our platform before I realized it's the plugin issue. Correct documentation will save others time. Thanks

**Comment by ahalim-intel** [comment]
I think the pciAddress filter is applicable to the accelerators as well and not having that implemented for accelerator was genuine miss IMO. We definitely should consider this PR. Thanks for @svallala for flagging this and submitting the solution.

**Review by adrianchiris — COMMENTED** [review]
Straightforward change

As stated in : https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#common-selectors

`pciAddresses` selector is common

we should really have a common method to filter devices according to defined common filters, (thought for improvement... not related to this PR.)

overall looks good, it would be great if you could extend `accelDeviceProvider_test.go` to include  filtering with this selector. 

https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/fb9fa79ae3c3a7ee2a18598e3c3314de6f72e0f1/pkg/accelerator/accelDeviceProvider_test.go#L126

**Review by zshi-redhat — APPROVED** [review]

**Comment by zshi-redhat** [comment]
@ahalim-intel @adrianchiris if you can give an approve, I will merge it.

**Comment by ahalim-intel** [comment]
/lgtm
echo @adrianchiris comment above about extending the test.

**Comment by svallala** [comment]
A completely different test is failing, locally if I reran the tests everything passed, so I assumed it is some transient failure that I could ignore. Can someone help me with this failure?

**Comment by svallala** [comment]
@zshi-redhat running the tests locally is working fine. Can you please help me with this error? Thanks

**Comment by zshi-redhat** [comment]
> @zshi-redhat running the tests locally is working fine. Can you please help me with this error? Thanks

@svallala Martin is attempting to fix the ghw test error at: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/312, once that's done, I will re-run the test in this PR.

**Comment by svallala** [comment]
Thanks @zshi-redhat

**Review by adrianchiris — APPROVED** [review]

**Review by martinkennelly — APPROVED** [review]

**Comment by zshi-redhat** [comment]
@svallala could you rebase against latest master and see if CI passes?  There were two CI issues fixed last week.

**Comment by svallala** [comment]
@zshi-redhat I rebased and the scripts have passed now.

**Comment by zshi-redhat** [comment]
> @zshi-redhat I rebased and the scripts have passed now.

thanks!

**Comment by zshi-redhat** [comment]
Merge it since we already have 3 approves and the latest change is just rebase against master (for including CI fixs).

**Comment by svallala** [comment]
thanks @zshi-redhat

**Pull request merged**
