### PR TITLE
Removing Travis

### PR DESCRIPTION
**Pull request by Eoghan1232**
Switching to ghcr as our image repository and depreciating travis following the closure of travis-ci.org.

### CODE REVIEW

**Comment by Eoghan1232** [comment]
@zshi-redhat

**Comment by zshi-redhat** [comment]
@Eoghan1232 This PR seems overlapping with part of https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/348 ?

**Comment by Eoghan1232** [comment]
> @Eoghan1232 This PR seems overlapping with part of #348 ?

Never spotted that. I can see there is overlap between the two. In #348 the travis.yaml is not removed. Otherwise it seems it contains all the changes I had in my PR here. 

What would be best to do? @zshi-redhat

**Comment by zshi-redhat** [comment]
> > @Eoghan1232 This PR seems overlapping with part of #348 ?
> 
> Never spotted that. I can see there is overlap between the two. In #348 the travis.yaml is not removed. Otherwise it seems it contains all the changes I had in my PR here.
> 
> What would be best to do? @zshi-redhat

I think we can leave this one to remove .travis.yaml and merge after #348 is done. wdyt?

**Comment by Eoghan1232** [comment]
> > > @Eoghan1232 This PR seems overlapping with part of #348 ?
> > 
> > 
> > Never spotted that. I can see there is overlap between the two. In #348 the travis.yaml is not removed. Otherwise it seems it contains all the changes I had in my PR here.
> > What would be best to do? @zshi-redhat
> 
> I think we can leave this one to remove .travis.yaml and merge after #348 is done. wdyt?

Yes, that would probably be best.

**Comment by adrianchiris** [comment]
@Eoghan1232 mind rebasing this PR ? i have merged #348. we can now move forward with removing `travis.yml`.

**Comment by Eoghan1232** [comment]
> @Eoghan1232 mind rebasing this PR ? i have merged #348. we can now move forward with removing `travis.yml`.

Done.

**Comment by Eoghan1232** [comment]
> > @Eoghan1232 mind rebasing this PR ? i have merged #348. we can now move forward with removing `travis.yml`.
> 
> Done.
@adrianchiris

**Review by adrianchiris — APPROVED** [review]
LGTM.

If you get the chance, please update commit msg to explain why this file is removed (project switched to github actions and this file is no longer needed)

**Comment by Eoghan1232** [comment]
> LGTM.
> 
> If you get the chance, please update commit msg to explain why this file is removed (project switched to github actions and this file is no longer needed)

Done.

**Comment by Eoghan1232** [comment]
> > LGTM.
> > If you get the chance, please update commit msg to explain why this file is removed (project switched to github actions and this file is no longer needed)
> 
> Done.

@adrianchiris @zshi-redhat 
Good to merge? 
I can't approve my own MR.

**Review by zshi-redhat — APPROVED** [review]

**Pull request merged**
